# Generated by Django 2.2.6 on 2020-11-07 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('total_quantity', models.IntegerField()),
                ('current_ppi', models.FloatField()),
                ('total_cost', models.FloatField()),
            ],
            options={
                'db_table': 'Inventory',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cost_per_item', models.FloatField()),
                ('total_cost', models.FloatField()),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inventory')),
            ],
            options={
                'db_table': 'Sales',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cost_per_item', models.FloatField()),
                ('total_cost', models.FloatField()),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inventory')),
            ],
            options={
                'db_table': 'Purchase',
            },
        ),
    ]
